name: aiu
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cpuonly   # Use 'cudatoolkit=xx.x' instead of 'cpuonly' if you have GPU support
  - -c conda-forge ultralytics
  - numpy
  - opencv
